version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'backend-db'
    environment: 
      - MONGO_INITDB_DATABASE=BUDGET-DB
      - MONGO_INITDB_USERNAME=dbadmin
      - MONGO_INITDB_PASSWORD=secret
    volumes:
      - ./mongo-volume:/data/db
    ports: 
      - '27017-27019:27017-27019'
  monthly-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
